### ISSUE TITLE
Can‘t play english audio stream

### ISSUE THREAD

**Issue by nkls23** [kodosexe/F1Hub#6] opened 2021-03-26 10:53 UTC
Hello its me again.

Got the feed going but I'm only getting the german audio channel to work. If I select the english one the feed dies and doesn't come back.

Any ideas on how to fix this? 

I love that 1080 50p goodness though!

Thanks!

**Comment by kodosexe** [comment] 2021-03-26 11:00
Hey, thanks for the report!

Once you are able to start the stream and mpv gets going, f1Hub's work is done, so I suspect either mpv or the stream itself to be the culprit.

Normally, you can switch the language in mpv by clicking on the speech bubble.

I'll test it out during practice today, though

**Comment by nkls23** [comment] 2021-03-26 11:15
Yeah thats what I suspected. F1TV might still be in alpha testing so who knows when they'll fix this.

Thanks for your help!

**Comment by kodosexe** [comment] 2021-03-26 11:16
I'm curious whether it worked on the website, though. Did you try it?

**Comment by nkls23** [comment] 2021-03-26 11:26
I can't login on their website because I keep getting the "something went wrong" message when I try to login. I did check the stream on the F1TV app and it was fine. 

So this and F1Viewer is my only hope at the moment to watch F1 on my computer.

**Comment by kodosexe** [comment] 2021-03-26 11:29
If you're on a vpn, you'll have to turn it off during login. You can reenable it afterwards, though

**Comment by nkls23** [comment] 2021-03-26 11:43
I see. I haven't tried that yet. Anyways got the english stream finally working now for F1 FP1. 

Thanks for your help!

**Comment by kodosexe** [comment] 2021-03-26 11:51
I don't have problems on my side either. Glad the problem is fixed!

I'll close this now.

**Closed by kodosexe** 2021-03-26 11:52 UTC
Labels: bug
